# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    PhpAmqpLib.Channel.AMQPExchange:
      class: PhpAmqpLib\Channel\AMQPChannel
      arguments:
        $connection: '@PhpAmqpLib.Connection.AMQPSocketConnection'
    PhpAmqpLib.Connection.AMQPSocketConnection:
      class: PhpAmqpLib\Connection\AMQPSocketConnection
      arguments:
        $host: localhost
        $port: 5672
        $user: mohsen
        $password: mohsen
        $vhost: /log
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
